[package]
name = "senringan-static"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
memmap2 = "0.5"
sha2 = "0.10"
goblin = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
